# Site settings
title: 'DongJuLee'
description: '동주의 성장 블로그'
url: 'http://noble17.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Lee Dong Ju'
  email: noble8543@gmail.com
  github_username:  noble17

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

#facebook
app_id:              430274870491769

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
ogp:
	  fb:
	    app_id: 430274870491769
	    
gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
